Repository teamforus/forus-frontend-react, pull requests merged in 2024-10, with the labels that each got.

#344 WCAG improvements for elements like checkboxes, toggles
  react/assets/forus-webshop/scss/_common/modals/modal-photo-cropper.scss
  react/src/dashboard/components/elements/select-control/hooks/useSelectControlKeyEventHandlers.tsx
  react/src/dashboard/components/elements/select-control/templates/SelectControlOptionsCountryCodes.tsx
  react/src/dashboard/components/elements/select-control/templates/elements/SelectControlOptionItem.tsx
  react/src/dashboard/helpers/wcag.ts
  react/src/webshop/components/elements/file-uploader/FileUploader.tsx
  react/src/webshop/components/elements/top-navbar/TopNavbar.tsx
  react/src/webshop/components/elements/top-navbar/TopNavbarSearch.tsx
  react/src/webshop/components/modals/ModalReimbursementConfirm.tsx
  react/src/webshop/components/modals/ModalShareVoucher.tsx
  react/src/webshop/components/modals/modal-photo-cropper/ModalPhotoCropper.tsx
  react/src/webshop/components/pages/identity-emails/PreferencesEmails.tsx
  react/src/webshop/components/pages/identity-security/Security2FA.tsx
  react/src/webshop/components/pages/identity-security/SecuritySessions.tsx
  react/src/webshop/components/pages/preferences-notifications/elements/NotificationPreferencesCards.tsx
  react/src/webshop/components/pages/search/Search.tsx
  react/src/webshop/components/pages/search/elements/SearchItemsList.tsx
  react/src/webshop/components/pages/vouchers-show/VouchersShow.tsx
  react/src/webshop/services/SearchService.ts
Labels: Urgency: High

#338 add hint for email input in the webshop sign-up form
  react/assets/forus-webshop/scss/_common/sections/blocks/block-sign_up.scss
  react/src/webshop/components/pages/auth/Start.tsx
Labels: Urgency: Medium

#353 fix submitted data format for fund request decline modal
  react/src/dashboard/components/modals/ModalFundRequestRecordsDecline.tsx
Labels: Urgency: High

#350 bump summernote
  package-lock.json
  package.json
Labels: Urgency: Low

#305 Add fund request redirect if user not authenticated, fund request style improvements on fund activate page
  react/assets/forus-webshop/resources/_webshop-common/assets/img/fund-request-success.png
  react/assets/forus-webshop/scss/_common/sections/blocks/block-sign_up.scss
  react/src/webshop/components/pages/auth/IdentityRestore.tsx
  react/src/webshop/components/pages/auth/Start.tsx
  react/src/webshop/components/pages/fund-requests-show/FundRequestsShow.tsx
  react/src/webshop/components/pages/funds-activate/FundActivate.tsx
  react/src/webshop/i18n/en/pages/fund-request.js
  react/src/webshop/i18n/nl/pages/fund-request.js
  react/src/webshop/router/routes.tsx
Labels: Urgency: High

#328 allow marking fund criteria as optional or required on the webshop
  react/assets/forus-webshop/scss/_common/components/_form.scss
  react/assets/forus-webshop/scss/_common/components/_ui-controls.scss
  react/src/dashboard/components/elements/forms/elements/FormGroupInfo.tsx
  react/src/dashboard/components/modals/ModalReservationCreate.tsx
  react/src/dashboard/components/modals/ModalVoucherCreate.tsx
  react/src/dashboard/components/modals/ModalVouchersUpload.tsx
  react/src/dashboard/components/pages/implementations-cms/ImplementationsCms.tsx
  react/src/dashboard/components/pages/organizations-funds-edit/OrganizationsFundsEdit.tsx
  react/src/dashboard/i18n/i18n-nl.js
  react/src/dashboard/i18n/nl/modals/modal-voucher-create.js
  react/src/webshop/components/elements/forms/FormLabel.tsx
  react/src/webshop/components/pages/funds-request/elements/steps/FundRequestStepCriteria.tsx
  react/src/webshop/props/models/Fund.ts
Labels: Urgency: High

#339 remove fund requests partially approved state and all states from rec…
  react/assets/forus-webshop/scss/_common/sections/blocks/block-sign_up.scss
  react/src/dashboard/components/modals/ModalFundRequestDecline.tsx
  react/src/dashboard/components/modals/ModalFundRequestRecordsDecline.tsx
  react/src/dashboard/components/pages/features/Features.tsx
  react/src/dashboard/components/pages/fund-requests-view/FundRequestsView.tsx
  react/src/dashboard/components/pages/fund-requests/FundRequests.tsx
  react/src/dashboard/props/models/FundRequest.tsx
  react/src/dashboard/props/models/FundRequestRecord.tsx
  react/src/dashboard/services/FundRequestValidatorService.ts
  react/src/webshop/components/pages/fund-requests-show/FundRequestsShow.tsx
  react/src/webshop/components/pages/fund-requests/elements/FundRequestCard.tsx
  react/src/webshop/components/pages/funds-activate/FundActivate.tsx
Labels: Urgency: Medium

#337 Webshop add payouts details
  react/assets/forus-webshop/resources/_webshop-common/assets/img/placeholders/payout.svg
  react/assets/forus-webshop/scss/_common/sections/blocks/block-fund-request.scss
  react/assets/forus-webshop/scss/_common/sections/blocks/block-payouts.scss
  react/assets/forus-webshop/scss/webshop.scss
  react/src/dashboard/props/models/FundRequest.tsx
  react/src/dashboard/props/models/PayoutTransaction.tsx
  react/src/webshop/components/elements/empty-value/EmptyValue.tsx
  react/src/webshop/components/elements/profile-menu/ProfileMenu.tsx
  react/src/webshop/components/pages/fund-requests-show/FundRequestsShow.tsx
  react/src/webshop/components/pages/payouts/Payouts.tsx
  react/src/webshop/components/pages/payouts/elements/PayoutCard.tsx
  react/src/webshop/components/pages/payouts/elements/PayoutCardDate.tsx
  react/src/webshop/components/pages/payouts/elements/PayoutCardLabel.tsx
  react/src/webshop/components/pages/payouts/elements/PayoutCardOverview.tsx
  react/src/webshop/i18n/i18n-nl.js
  react/src/webshop/i18n/nl/directives/profile-menu.js
  react/src/webshop/i18n/nl/pages/payouts.js
  react/src/webshop/router/routes.tsx
  react/src/webshop/services/PayoutTransactionService.ts
Labels: Urgency: High

#391 UX improvements to the fund request page
  react/assets/forus-platform/resources/_platform-common/assets/img/fund-request-icon.svg
  react/assets/forus-platform/scss/_common/blocks/block-fund-request-assigned.scss
  react/assets/forus-platform/scss/_common/dashboard.scss
  react/src/dashboard/components/elements/block-card-notes/BlockCardNotes.tsx
  react/src/dashboard/components/elements/key-value/KeyValueItem.tsx
  react/src/dashboard/components/modals/ModalFundRequestClarify.tsx
  react/src/dashboard/components/pages/fund-requests-view/FundRequestsView.tsx
  react/src/dashboard/components/pages/fund-requests/FundRequests.tsx
  react/src/dashboard/i18n/i18n-nl.js
Labels: Urgency: High

#387 Add extra description to fund criteria
  react/assets/forus-platform/scss/_common/blocks/block-critera-editor.scss
  react/assets/forus-webshop/scss/_common/sections/blocks/block-sign_up.scss
  react/src/dashboard/components/elements/forms/markdown-editor/MarkdownEditor.tsx
  react/src/dashboard/components/elements/fund-criteria-editor/FundCriteriaEditorItem.tsx
  react/src/dashboard/components/modals/ModalFundCriteriaDescriptionEdit.tsx
  react/src/dashboard/i18n/nl/i18n-components.js
  react/src/dashboard/i18n/nl/modals/modal-fund-criteria-description.js
  react/src/dashboard/props/models/FundCriterion.tsx
  react/src/webshop/components/pages/funds-request/elements/steps/FundRequestStepCriteria.tsx
Labels: Urgency: High

#317 reimbursements dashboard page enhancements
  react/src/dashboard/components/elements/block-reimbursement-categories/BlockReimbursementCategories.tsx
  react/src/dashboard/components/pages/reimbursements/Reimbursements.tsx
Labels: Urgency: High, needs_release

#401 Show approved fund request only if it created between fund start and end dates on fund activate page
  react/src/webshop/components/pages/funds-activate/FundActivate.tsx
Labels: Urgency: High

#348 hide pagination if provider products list is empty
  react/src/dashboard/components/pages/fund-provider/elements/BudgetFundProducts.tsx
  react/src/dashboard/components/pages/fund-provider/elements/BudgetFundSponsorProducts.tsx
  react/src/dashboard/components/pages/fund-provider/elements/SubsidyFundProducts.tsx
  react/src/dashboard/components/pages/fund-provider/elements/SubsidyFundSponsorProducts.tsx
Labels: Urgency: Medium

#384 add number to vouchers
  react/assets/forus-webshop/scss/_common/sections/blocks/vouchers.scss
  react/src/dashboard/components/pages/vouchers-view/VouchersViewComponent.tsx
  react/src/dashboard/components/pages/vouchers/elements/VouchersTableRow.tsx
  react/src/dashboard/i18n/en/pages/vouchers.js
  react/src/dashboard/i18n/nl/pages/vouchers.js
  react/src/dashboard/props/models/Voucher.tsx
  react/src/dashboard/services/VoucherService.ts
  react/src/webshop/components/elements/lists/funds-list/FundsListItem.tsx
  react/src/webshop/components/elements/select-control/templates/SelectControlOptionsVouchers.tsx
  react/src/webshop/components/elements/select-control/templates/elements/SelectControlOptionItemVoucher.tsx
  react/src/webshop/components/modals/ModalDeactivateVoucher.tsx
  react/src/webshop/components/modals/ModalPhysicalCardType.tsx
  react/src/webshop/components/modals/ModalPhysicalCardUnlink.tsx
  react/src/webshop/components/modals/ModalShareVoucher.tsx
  react/src/webshop/components/modals/modal-product-reserve/ModalProductReserve.tsx
  react/src/webshop/components/pages/funds-activate/FundActivate.tsx
  react/src/webshop/components/pages/funds-request/FundRequest.tsx
  react/src/webshop/components/pages/funds-show/FundsShow.tsx
  react/src/webshop/components/pages/products-show/elements/ProductFundsCard.tsx
  react/src/webshop/components/pages/vouchers-show/VouchersShow.tsx
  react/src/webshop/components/pages/vouchers/elements/VoucherCard.tsx
  react/src/webshop/router/routes.tsx
  react/src/webshop/services/AuthService.ts
  react/src/webshop/services/PhysicalCardsRequestService.ts
  react/src/webshop/services/PhysicalCardsService.ts
  react/src/webshop/services/VoucherService.ts
Labels: Urgency: High

#347 fix banner overlay patterns for webshop homepage
  react/src/webshop/components/pages/home/Home.tsx
Labels: Urgency: Low

#372 Hide prices for budget fund in fund offers modal
  react/src/dashboard/components/modals/ModalFundOffers.tsx
Labels: Urgency: Low

#386 Fix reversed rows in csv upload
  react/src/dashboard/components/pages/csv_validations/elements/CSVUpload.tsx
Labels: Urgency: Medium

#351 fix product reservation modal issue with long user note description a…
  react/src/webshop/components/modals/modal-product-reserve/ModalProductReserve.tsx
Labels: Urgency: Low

#315 add duplicates picker modal confirmation for low amount vouchers upload
  react/src/dashboard/components/modals/ModalDuplicatesPicker.tsx
  react/src/dashboard/components/modals/ModalPayoutsUpload.tsx
  react/src/dashboard/components/modals/ModalReservationUpload.tsx
  react/src/dashboard/components/modals/ModalVoucherCreate.tsx
  react/src/dashboard/components/modals/ModalVoucherTransactionsUpload.tsx
  react/src/dashboard/components/modals/ModalVouchersUpload.tsx
  react/src/dashboard/components/pages/csv_validations/elements/CSVUpload.tsx
  react/src/dashboard/services/PrevalidationService.ts
Labels: Urgency: Medium

#417 organizations filter refactoring
  react/src/webshop/components/pages/funds-pre-check/FundsPreCheck.tsx
  react/src/webshop/components/pages/funds/Funds.tsx
  react/src/webshop/components/pages/products/Products.tsx
  react/src/webshop/components/pages/reservations/Reservations.tsx
  react/src/webshop/components/pages/search/Search.tsx
Labels: Urgency: High

#415 fix Vergoedingen webshop navbar search toggle issue
  react/src/dashboard/components/elements/click-outside/ClickOutside.tsx
Labels: Urgency: High
