Repository teamforus/forus-frontend-react, pull requests merged in 2024-09, with the labels that each got.

#271 Add payment type to sponsor transactions table
  react/src/dashboard/components/pages/transaction-settings/TransactionSettings.tsx
  react/src/dashboard/components/pages/transactions/Transactions.tsx
  react/src/dashboard/components/pages/vouchers-view/VouchersViewComponent.tsx
  react/src/dashboard/components/pages/vouchers/elements/VouchersTableRow.tsx
  react/src/dashboard/components/pages/vouchers/elements/VouchersTableRowActions.tsx
  react/src/dashboard/i18n/i18n-nl.js
  react/src/dashboard/i18n/nl/pages/transactions.js
  react/src/dashboard/layout/elements/aside/LayoutAsideProvider.tsx
  react/src/dashboard/layout/elements/aside/LayoutAsideSponsor.tsx
  react/src/dashboard/props/models/Transaction.tsx
Labels: Urgency: High, Urgency: Medium

#270 Update styles for bulk and csv upload forms
  react/assets/forus-platform/resources/_platform-common/assets/img/upload-bg.png
  react/assets/forus-platform/scss/_common/components/buttons.scss
  react/assets/forus-platform/scss/_common/dashboard.scss
  react/assets/forus-platform/scss/_common/modals/modal-bulk-upload.scss
  react/src/dashboard/components/modals/ModalReservationUpload.tsx
  react/src/dashboard/components/modals/ModalVoucherTransactionsUpload.tsx
  react/src/dashboard/components/modals/ModalVouchersUpload.tsx
  react/src/dashboard/components/pages/csv_validations/CsvValidations.tsx
  react/src/dashboard/components/pages/csv_validations/elements/CSVUpload.tsx
  react/src/dashboard/helpers/string.ts
Labels: Urgency: High

#259 Remove stepper for adults_nth
  react/src/webshop/services/FundService.ts
Labels: blocked

#288 generic placeholder fund request
  react/src/webshop/components/pages/funds-request/elements/steps/FundRequestStepCriteria.tsx
Labels: Urgency: Medium

#265 add tooltips to the transaction details page
  react/assets/forus-platform/scss/_common/dashboard.scss
  react/src/dashboard/components/elements/tooltip/Tooltip.tsx
  react/src/dashboard/components/pages/transaction-settings/TransactionSettings.tsx
Labels: Urgency: Medium

#287 select controls: fix focus outlines and keyboard navigation enhancements
  react/assets/forus-webshop/scss/_common/components/_form.scss
  react/assets/forus-webshop/scss/_common/sections/blocks/block-label-tabs.scss
  react/assets/forus-webshop/scss/_common/sections/blocks/vouchers.scss
  react/assets/forus-webshop/scss/style-webshop-general-vars.scss
  react/src/dashboard/components/elements/select-control/SelectControl.tsx
  react/src/dashboard/components/elements/select-control/hooks/useSelectControlKeyEventHandlers.tsx
  react/src/dashboard/components/elements/select-control/templates/SelectControlOptions.tsx
  react/src/dashboard/components/elements/select-control/templates/SelectControlOptionsCountryCodes.tsx
  react/src/dashboard/components/elements/select-control/templates/SelectControlOptionsFund.tsx
  react/src/dashboard/components/elements/select-control/templates/SelectControlOptionsOrganization.tsx
  react/src/dashboard/components/elements/select-control/templates/elements/SelectControlOptionItem.tsx
  react/src/webshop/components/elements/select-control/templates/SelectControlOptionsVouchers.tsx
Labels: Urgency: Medium

#261 Add provider products required for funds and notification modal for provider
  react/assets/forus-platform/resources/_platform-common/assets/img/alert-icons/warning-outline.svg
  react/assets/forus-platform/resources/_platform-common/assets/img/alert-icons/warning.svg
  react/assets/forus-platform/scss/_common/blocks/block-info-with-icon.scss
  react/assets/forus-platform/scss/_common/blocks/block-provider-products-required.scss
  react/assets/forus-platform/scss/_common/dashboard.scss
  react/assets/forus-platform/scss/_common/modals/modal-provider-products-required.scss
  react/src/dashboard/Dashboard.tsx
  react/src/dashboard/components/elements/funds-provider-products-required-table/FundsProviderProductsRequiredTable.tsx
  react/src/dashboard/components/modals/ModalFundsProviderProductsRequired.tsx
  react/src/dashboard/components/pages/organizations-funds-edit/OrganizationsFundsEdit.tsx
  react/src/dashboard/components/pages/provider-overview/ProviderOverview.tsx
  react/src/dashboard/components/pages/provider-overview/elements/ProductsRequiredNotification.tsx
  react/src/dashboard/i18n/nl/i18n-components.js
  react/src/dashboard/modules/provider_notification_product_required/ProviderNotificationProductRequired.tsx
  react/src/dashboard/modules/storage/useStrorrageService.ts
  react/src/dashboard/props/models/Fund.tsx
  react/src/dashboard/services/ProviderFundService.ts
Labels: Urgency: Medium

#300 Add wadenheuvel css include
  react/assets/forus-webshop/scss/style-webshop-wadenheuvel-vars.scss
  react/assets/forus-webshop/scss/style-webshop-wadenheuvel.scss
Labels: Urgency: Low

#301 Updating urls to Dutch
  react/src/dashboard/router/routes.tsx
Labels: Urgency: Low

#316 display fund request clarification texts in multiple lines
  react/src/dashboard/components/elements/multiline-text/MultilineText.tsx
  react/src/dashboard/components/pages/fund-requests-view/elements/record-tabs/FundRequestRecordClarificationsTab.tsx
  react/src/webshop/components/pages/fund-requests-show/elements/FundRequestRecordClarificationCard.tsx
Labels: Urgency: Medium

#323 minor wcag and visual fixes and providers pagination issue in some cases
  react/assets/forus-webshop/scss/_common/components/table-pagination.scss
  react/assets/forus-webshop/scss/_common/sections/blocks/block-bookmark-toggle.scss
  react/assets/forus-webshop/scss/_common/sections/blocks/block-sign_up.scss
  react/src/dashboard/components/pages/auth/SignUpProvider.tsx
  react/src/dashboard/components/pages/auth/SignUpValidator.tsx
  react/src/dashboard/components/pages/auth/elements/sign-up-steps/SignUpStepGeneralInfo.tsx
  react/src/dashboard/components/pages/auth/elements/sign-up-steps/SignUpStepOrganizationAdd.tsx
  react/src/dashboard/components/pages/auth/elements/sign-up-steps/SignUpStepOrganizationSelect.tsx
  react/src/webshop/components/pages/funds-activate/FundActivate.tsx
  react/src/webshop/components/pages/funds-request/elements/steps/FundRequestStepConfirmCriteria.tsx
  react/src/webshop/components/pages/funds-request/elements/steps/FundRequestStepContactInformation.tsx
  react/src/webshop/components/pages/funds-request/elements/steps/FundRequestStepCriteria.tsx
  react/src/webshop/components/pages/funds-request/elements/steps/FundRequestStepCriteriaOverview.tsx
  react/src/webshop/components/pages/funds-request/elements/steps/FundRequestStepEmailSetup.tsx
  react/src/webshop/components/pages/funds-request/elements/steps/FundRequestValuesOverview.tsx
  react/src/webshop/components/pages/providers/Providers.tsx
Labels: Urgency: Low

#285 Fix duplicated email sent block on webshop
  react/src/webshop/components/elements/top-navbar/TopNavbar.tsx
  react/src/webshop/components/pages/auth/Start.tsx
  react/src/webshop/layout/elements/LayoutMobileMenu.tsx
Labels: Urgency: Medium

#333 fix prevalidations export fund-selector
  react/src/dashboard/components/pages/csv_validations/elements/PrevalidatedTable.tsx
Labels: Urgency: Hotfix

#330 Minor translations
  react/src/dashboard/components/elements/fund-criteria-editor/FundCriteriaEditorItem.tsx
  react/src/webshop/components/elements/lists/funds-list/templates/FundsListItemPreCheck.tsx
Labels: Urgency: Low, Urgency: Medium

#325 Add record type validation for csv prevalidations data
  react/src/dashboard/components/pages/csv_validations/elements/CSVUpload.tsx
Labels: Urgency: High

#256 Temporary replace summernote package with github repo for fixing table insert issue
  package-lock.json
  package.json
Labels: Urgency: Medium
