Repository teamforus/forus-frontend-react, pull requests merged in 2024-08, with the labels that each got.

#243 Change focus order for mobile header and menu
  react/src/webshop/components/elements/top-navbar/TopNavbar.tsx
  react/src/webshop/layout/Layout.tsx
  react/src/webshop/layout/elements/LayoutMobileMenu.tsx
Labels: Urgency: Low

#248 Add state group filter to sponsor providers
  react/assets/forus-platform/scss/_common/components/buttons.scss
  react/assets/forus-platform/scss/_common/components/forms.scss
  react/assets/forus-platform/scss/_common/dashboard.scss
  react/src/dashboard/components/pages/sponsor-provider-organizations/SponsorProviderOrganizations.tsx
Labels: Urgency: High

#252 tables top scroll bar for vouchers and transactions and scrollable ta…
  react/assets/forus-platform/scss/_common/components/tables.scss
  react/assets/forus-platform/scss/_common/includes/helpers.scss
  react/src/dashboard/components/elements/tables/TableTopScroller.tsx
  react/src/dashboard/components/pages/financial-dashboard-overview/elements/FinancialOverviewFundsBudgetTableItem.tsx
  react/src/dashboard/components/pages/organizations-funds/OrganizationFunds.tsx
  react/src/dashboard/components/pages/reimbursements/Reimbursements.tsx
  react/src/dashboard/components/pages/sponsor-fund-unsubscriptions/elements/SponsorFundUnsubscriptionTableItem.tsx
  react/src/dashboard/components/pages/sponsor-provider-organizations/elements/ProvidersTableItem.tsx
  react/src/dashboard/components/pages/sponsor-provider-organizations/elements/ProvidersTableItemFunds.tsx
  react/src/dashboard/components/pages/transactions/Transactions.tsx
  react/src/dashboard/components/pages/vouchers/Vouchers.tsx
  react/src/dashboard/components/pages/vouchers/elements/VouchersTableRow.tsx
Labels: Urgency: Medium

#251 home page products block cms
  react/assets/forus-webshop/scss/vergoedingen/includes/shame.scss
  react/src/dashboard/components/elements/forms/markdown-editor/MarkdownEditor.tsx
  react/src/dashboard/components/pages/implementations-cms-page/elements/ImplementationsCmsHomeProductsBlockEditor.tsx
  react/src/dashboard/components/pages/implementations-cms-page/elements/ImplementationsCmsPageForm.tsx
  react/src/dashboard/components/pages/implementations-cms/elements/ImplementationsCmsPages.tsx
  react/src/dashboard/props/models/Implementation.tsx
  react/src/dashboard/props/models/ImplementationPage.tsx
  react/src/dashboard/services/ConfigService.ts
  react/src/webshop/components/elements/block-products/BlockProducts.tsx
  react/src/webshop/components/pages/home/Home.tsx
  react/src/webshop/props/models/ImplementationPage.ts
Labels: Urgency: Medium

#244 add docker files
  .dockerignore
  Dockerfile
  docker-compose.yml
  docker/docker-compose/Dockerfile
  docker/docker-compose/apache2/httpd-vhosts.conf
  docker/docker-compose/apache2/httpd.conf
  env.example.js
  readme-docker.md
Labels: Urgency: Medium

#247 combine voucher pages
  react/assets/forus-platform/resources/_platform-common/assets/img/menu/icon-product_voucher-active.svg
  react/assets/forus-platform/resources/_platform-common/assets/img/menu/icon-product_voucher-hover.svg
  react/assets/forus-platform/resources/_platform-common/assets/img/menu/icon-product_voucher.svg
  react/assets/forus-platform/scss/_common/components/tables.scss
  react/assets/forus-platform/scss/_common/dashboard.scss
  react/assets/forus-platform/scss/_common/includes/helpers.scss
  react/src/dashboard/components/elements/forms/elements/FormGroupInfo.tsx
  react/src/dashboard/components/elements/tables/TableTopScroller.tsx
  react/src/dashboard/components/modals/ModalFundSelect.tsx
  react/src/dashboard/components/modals/ModalReservationUpload.tsx
  react/src/dashboard/components/modals/ModalVoucherCreate.tsx
  react/src/dashboard/components/modals/ModalVoucherTransactionsUpload.tsx
  react/src/dashboard/components/modals/ModalVouchersUpload.tsx
  react/src/dashboard/components/pages/csv_validations/elements/CSVUpload.tsx
  react/src/dashboard/components/pages/financial-dashboard-overview/elements/FinancialOverviewFundsBudgetTableItem.tsx
  react/src/dashboard/components/pages/identitities-show/elements/IdentityVouchersCard.tsx
  react/src/dashboard/components/pages/organizations-funds/OrganizationFunds.tsx
  react/src/dashboard/components/pages/reimbursements/Reimbursements.tsx
  react/src/dashboard/components/pages/sponsor-fund-unsubscriptions/elements/SponsorFundUnsubscriptionTableItem.tsx
  react/src/dashboard/components/pages/sponsor-provider-organizations/elements/ProvidersTableItem.tsx
  react/src/dashboard/components/pages/sponsor-provider-organizations/elements/ProvidersTableItemFunds.tsx
  react/src/dashboard/components/pages/transactions/Transactions.tsx
  react/src/dashboard/components/pages/vouchers-view/VouchersViewComponent.tsx
  react/src/dashboard/components/pages/vouchers/ProductVouchers.tsx
  react/src/dashboard/components/pages/vouchers/Vouchers.tsx
  react/src/dashboard/components/pages/vouchers/elements/VouchersTableFilters.tsx
  react/src/dashboard/components/pages/vouchers/elements/VouchersTableHeader.tsx
  react/src/dashboard/components/pages/vouchers/elements/VouchersTableRow.tsx
  react/src/dashboard/i18n/i18n-nl.js
  react/src/dashboard/i18n/nl/i18n-pages.js
  react/src/dashboard/i18n/nl/modals/modal-voucher-create.js
  react/src/dashboard/i18n/nl/pages/product-vouchers.js
  react/src/dashboard/i18n/nl/pages/vouchers.js
  react/src/dashboard/layout/elements/aside/LayoutAsideSponsor.tsx
  react/src/dashboard/router/routes.tsx
  react/src/dashboard/services/VoucherService.ts
Labels: Urgency: High

#262 Update texts on dashboard
  react/src/dashboard/components/pages/organizations-funds-edit/OrganizationsFundsEdit.tsx
Labels: Scope: Tiny, Urgency: Low

#276 Remove external validators
  react/assets/forus-platform/resources/_platform-common/assets/img/features/img/external-funds/banner.jpg
  react/assets/forus-platform/resources/_platform-common/assets/img/menu/icon-fund_validations-active.svg
  react/assets/forus-platform/resources/_platform-common/assets/img/menu/icon-fund_validations-hover.svg
  react/assets/forus-platform/resources/_platform-common/assets/img/menu/icon-fund_validations.svg
  react/assets/forus-platform/resources/_platform-common/assets/img/menu/icon-validators_shortlist-active.svg
  react/assets/forus-platform/resources/_platform-common/assets/img/menu/icon-validators_shortlist-hover.svg
  react/assets/forus-platform/resources/_platform-common/assets/img/menu/icon-validators_shortlist.svg
  react/src/dashboard/components/elements/fund-criteria-editor/FundCriteriaEditor.tsx
  react/src/dashboard/components/elements/fund-criteria-editor/FundCriteriaEditorItem.tsx
  react/src/dashboard/components/elements/fund-criteria-editor/FundCriteriaEditorItemExternalValidators.tsx
  react/src/dashboard/components/pages/external-validators/ExternalValidators.tsx
  react/src/dashboard/components/pages/external_funds/ExternalFunds.tsx
  react/src/dashboard/components/pages/fund-requests-view/FundRequestsView.tsx
  react/src/dashboard/components/pages/fund-requests/FundRequests.tsx
  react/src/dashboard/components/pages/organizations-funds-edit/OrganizationsFundsEdit.tsx
  react/src/dashboard/components/pages/organizations-funds-show/elements/OrganizationsFundsShowCriteriaCard.tsx
  react/src/dashboard/hooks/usePushApiError.tsx
  react/src/dashboard/i18n/en/i18n-components.js
  react/src/dashboard/i18n/i18n-nl.js
  react/src/dashboard/i18n/nl/i18n-components.js
  react/src/dashboard/i18n/nl/i18n-modals-danger_zone.js
  react/src/dashboard/i18n/nl/modals/danger-zone/remove-external-validator.js
  react/src/dashboard/layout/elements/aside/LayoutAsideSponsor.tsx
  react/src/dashboard/layout/elements/aside/LayoutAsideValidator.tsx
  react/src/dashboard/props/models/ExternalFund.tsx
  react/src/dashboard/props/models/FundCriterion.tsx
  react/src/dashboard/props/models/FundCriterionExternalValidator.tsx
  react/src/dashboard/props/models/FundRequest.tsx
  react/src/dashboard/props/models/FundRequestRecord.tsx
  react/src/dashboard/props/models/Organization.tsx
  react/src/dashboard/router/routes.tsx
  react/src/dashboard/services/OrganizationService.ts
Labels: Urgency: Medium

#275 Change checkbox styles wcag
  react/assets/forus-webshop/scss/_common/components/_form.scss
  react/assets/forus-webshop/scss/style-webshop-general-vars.scss
Labels: Urgency: High

#254 add voucher amount visible field to funds
  react/src/dashboard/components/pages/organizations-funds-edit/OrganizationsFundsEdit.tsx
Labels: Urgency: Medium, blocked

#264 fix an issue with voucher export and boolean type for filters
  react/src/dashboard/components/pages/vouchers/elements/VouchersTableFilters.tsx
Labels: Urgency: Medium

#263 make the implementation blocks sortable
  react/assets/forus-platform/scss/_common/blocks/block-implementation-blocks-editor.scss
  react/src/dashboard/components/pages/implementations-cms-page/elements/ImplementationsBlockEditor.tsx
  react/src/dashboard/components/pages/implementations-cms-page/elements/ImplementationsBlockEditorItem.tsx
  react/src/dashboard/components/pages/implementations-cms-page/elements/ImplementationsCmsPageForm.tsx
Labels: Urgency: Medium

#274 Change product bookmark icon css colors wcag
  react/assets/forus-webshop/scss/_common/sections/blocks/block-bookmark-toggle.scss
  react/src/webshop/components/elements/lists/products-list/templates/ProductsListItemList.tsx
  react/src/webshop/components/pages/products-show/ProductsShow.tsx
Labels: Urgency: High
