Repository teamforus/forus-frontend-react, pull requests merged in 2024-12, with the labels that each got.

#445 fix DigiD expired block on mobile devices
  react/src/webshop/components/pages/funds-request/FundRequest.tsx
Labels: Urgency: Medium

#437 Fix exception with translator in notifications dropdown
  react/src/dashboard/layout/elements/blocks/HeaderNotifications.tsx
Labels: Urgency: Low

#411 Add control type for record types
  react/src/dashboard/props/models/RecordType.tsx
  react/src/webshop/components/pages/funds-request/FundRequest.tsx
  react/src/webshop/services/FundService.ts
Labels: Urgency: Medium

#389 add fund formula products details to pre-check
  react/assets/forus-webshop/scss/_common/sections/blocks/block-fund-pre-check-result.scss
  react/assets/forus-webshop/scss/_common/sections/blocks/block-fund-pre-check.scss
  react/src/webshop/components/elements/lists/funds-list/templates/FundsListItemPreCheck.tsx
  react/src/webshop/components/pages/funds-pre-check/FundsPreCheck.tsx
  react/src/webshop/services/types/PreCheckTotals.ts
Labels: Urgency: Low

#498 revert react-router-dom to 6.27.0
  package-lock.json
  package.json
  react/src/dashboard/components/pages/auth/IdentityRestore.tsx
  react/src/webshop/components/modals/ModalIdentityProxyExpired.tsx
  react/src/webshop/components/pages/auth/IdentityRestore.tsx
Labels: Urgency: High

#383 add feature for excluding funds from pre-check results
  react/assets/forus-platform/resources/_platform-common/assets/img/pre-check-funds-logo.svg
  react/assets/forus-platform/scss/_common/dashboard.scss
  react/assets/forus-platform/scss/_common/includes/common.scss
  react/assets/forus-webshop/scss/_common/components/_ui-controls.scss
  react/assets/forus-webshop/scss/_common/sections/blocks/block-fund-pre-check-result.scss
  react/src/dashboard/components/elements/empty-card/EmptyCard.tsx
  react/src/dashboard/components/elements/forms/ui-controls/UIControlStep.tsx
  react/src/dashboard/components/modals/ModalPreCheckEditFundExclusions.tsx
  react/src/dashboard/components/pages/pre-check/PreCheck.tsx
  react/src/dashboard/components/pages/pre-check/cards/PreCheckExclusionsCard.tsx
  react/src/dashboard/i18n/nl/i18n-modals-danger_zone.js
  react/src/dashboard/i18n/nl/modals/danger-zone/exclude_pre_check_fund.js
  react/src/dashboard/props/models/Fund.tsx
  react/src/dashboard/services/FundService.ts
  react/src/webshop/components/elements/lists/funds-list/templates/FundsListItemPreCheck.tsx
  react/src/webshop/components/pages/funds-pre-check/FundsPreCheck.tsx
  react/src/webshop/services/types/PreCheckTotals.ts
Labels: Urgency: Medium

#447 fix an issue with csv vouchers upload when 'all funds' are selected
  react/src/dashboard/components/modals/ModalVouchersUpload.tsx
Labels: Urgency: Low

#475 Fix google map info window close icon
  react/assets/forus-webshop/scss/_common/components/_map-card.scss
  react/assets/forus-webshop/scss/_common/includes/shame.scss
  react/assets/forus-webshop/scss/_common/sections/blocks/block-map-office-card.scss
  react/src/dashboard/components/elements/google-map/GoogleMap.tsx
  react/src/webshop/components/elements/map-markers/MapMarkerProviderOffice.tsx
  react/src/webshop/components/elements/map-markers/MapMarkerProviderOfficeView.tsx
Labels: Urgency: Medium
