Repository teamforus/forus-frontend-react, pull requests merged in 2024-06, with the labels that each got.

#113 Migrate fund pages
  react/assets/forus-platform/scss/_common/components/forms.scss
  react/assets/forus-platform/scss/_common/dashboard.scss
  react/assets/forus-platform/scss/_common/dropdown/dropdown-actions.scss
  react/assets/forus-platform/scss/_common/includes/common.scss
  react/src/dashboard/components/elements/faq-editor-funds/FaqEditor.tsx
  react/src/dashboard/components/elements/faq-editor-funds/FaqEditorItem.tsx
  react/src/dashboard/components/elements/forms/controls/MultiSelectControl.tsx
  react/src/dashboard/components/elements/fund-criteria-editor/FundCriteriaEditor.tsx
  react/src/dashboard/components/elements/fund-criteria-editor/FundCriteriaEditorItem.tsx
  react/src/dashboard/components/elements/select-control/SelectControl.tsx
  react/src/dashboard/components/elements/select-control/templates/SelectControlOptions.tsx
  react/src/dashboard/components/elements/tables/TableRowActions.tsx
  react/src/dashboard/components/elements/tooltip/Tooltip.tsx
  react/src/dashboard/components/modals/ModalFundCriteriaDescriptionEdit.tsx
  react/src/dashboard/components/modals/ModalFundInviteProviders.tsx
  react/src/dashboard/components/modals/ModalFundTopUp.tsx
  react/src/dashboard/components/pages/identitities-show/IdentitiesShow.tsx
  react/src/dashboard/components/pages/identitities-show/elements/IdentityVouchersCard.tsx
  react/src/dashboard/components/pages/organizations-funds-edit/OrganizationsFundsEdit.tsx
  react/src/dashboard/components/pages/organizations-funds-edit/elements/FundConfigContactInfoEditor.tsx
  react/src/dashboard/components/pages/organizations-funds-security/OrganizationsFundsSecurity.tsx
  react/src/dashboard/components/pages/organizations-funds-security/elements/OrganizationsFundsSecurityAuth2FAForm.tsx
  react/src/dashboard/components/pages/organizations-funds-show/OrganizationsFundsShow.tsx
  react/src/dashboard/components/pages/organizations-funds/OrganizationFunds.tsx
  react/src/dashboard/components/pages/organizations-security/OrganizationsSecurity.tsx
  react/src/dashboard/i18n/i18n-nl.js
  react/src/dashboard/modules/state_router/Router.tsx
  react/src/dashboard/modules/state_router/StateNavLink.tsx
  react/src/dashboard/props/models/Faq.tsx
  react/src/dashboard/props/models/Fund.tsx
  react/src/dashboard/props/models/FundCriterion.tsx
  react/src/dashboard/props/models/FundFormulaProduct.tsx
  react/src/dashboard/props/models/FundTopUpTransaction.tsx
  react/src/dashboard/props/models/Organization.tsx
  react/src/dashboard/props/models/RecordType.tsx
  react/src/dashboard/props/models/Sponsor/Identity.tsx
  react/src/dashboard/props/models/Voucher.tsx
  react/src/dashboard/router/routes.tsx
  react/src/dashboard/services/ClipboardService.ts
  react/src/dashboard/services/FaqService.ts
  react/src/dashboard/services/FundService.ts
  react/src/dashboard/services/OrganizationService.ts
  react/src/dashboard/services/ProductService.ts
  react/src/dashboard/services/RecordTypeService.ts
  react/src/dashboard/services/TagService.ts
  react/src/dashboard/services/exports/useFundIdentitiesExportService.tsx
  react/src/dashboard/services/useFundProviderInvitationsService.ts
  react/src/webshop/components/pages/funds-pre-check/FundsPreCheck.tsx
  react/src/webshop/components/pages/funds/Funds.tsx
  react/src/webshop/props/models/Fund.ts
  react/src/webshop/props/models/FundFormula.ts
Labels: Urgency: High

#116 Migrate BI Connection page
  react/assets/forus-platform/scss/_common/blocks/block-bi-info.scss
  react/assets/forus-platform/scss/_common/blocks/block-info-box.scss
  react/assets/forus-platform/scss/_common/components/forms.scss
  react/assets/forus-platform/scss/_common/landing.scss
  react/src/dashboard/components/elements/auth2fa-restriction/Auth2FARestriction.tsx
  react/src/dashboard/components/pages/bi-connection/BiConnection.tsx
  react/src/dashboard/hooks/useCopyToClipboard.tsx
  react/src/dashboard/i18n/nl/pages/bi-connection.pug.i18n.js
  react/src/dashboard/props/models/BiConnection.tsx
  react/src/dashboard/props/models/BiConnectionDataType.tsx
  react/src/dashboard/props/models/Identity2FAState.tsx
  react/src/dashboard/router/routes.tsx
  react/src/dashboard/services/BiConnectionService.ts
  react/src/dashboard/services/ClipboardService.ts
Labels: Urgency: High

#87 Add financial dashboard and financial overview
  package-lock.json
  package.json
  react/assets/forus-platform/scss/_common/blocks/block-financial-dashboard.scss
  react/assets/forus-platform/scss/_common/components/tables.scss
  react/assets/forus-platform/scss/_common/includes/common.scss
  react/src/dashboard/components/pages/financial-dashboard-overview/FinancialDashboardOverview.tsx
  react/src/dashboard/components/pages/financial-dashboard-overview/elements/FinancialOverviewFundsBudgetTable.tsx
  react/src/dashboard/components/pages/financial-dashboard-overview/elements/FinancialOverviewFundsBudgetTableItem.tsx
  react/src/dashboard/components/pages/financial-dashboard-overview/elements/FinancialOverviewFundsTable.tsx
  react/src/dashboard/components/pages/financial-dashboard-overview/hooks/useExportFunds.tsx
  react/src/dashboard/components/pages/financial-dashboard/FinancialDashboard.tsx
  react/src/dashboard/components/pages/financial-dashboard/elements/FinancialChart.tsx
  react/src/dashboard/components/pages/financial-dashboard/elements/FinancialFilter.tsx
  react/src/dashboard/components/pages/financial-dashboard/elements/FinancialFilters.tsx
  react/src/dashboard/components/pages/financial-dashboard/elements/FinancialStatistics.tsx
  react/src/dashboard/components/pages/financial-dashboard/elements/ProviderFinancialTable.tsx
  react/src/dashboard/components/pages/financial-dashboard/elements/ProviderFinancialTablesTransactions.tsx
  react/src/dashboard/components/pages/financial-dashboard/types/FinancialStatisticTypes.ts
  react/src/dashboard/i18n/i18n-nl.js
  react/src/dashboard/props/models/Fund.tsx
  react/src/dashboard/router/routes.tsx
  react/src/dashboard/services/FundService.ts
  react/src/dashboard/services/OrganizationService.ts
  react/src/webshop/props/models/Fund.ts
Labels: Urgency: High

#76 Add transaction bulk page, add upload transactions modal
  package-lock.json
  package.json
  react/assets/forus-platform/scss/_common/blocks/block-financial-dashboard.scss
  react/assets/forus-platform/scss/_common/components/buttons.scss
  react/assets/forus-platform/scss/_common/components/tables.scss
  react/assets/forus-platform/scss/_common/includes/common.scss
  react/src/dashboard/components/elements/empty-card/EmptyCard.tsx
  react/src/dashboard/components/elements/key-value/KeyValueItem.tsx
  react/src/dashboard/components/modals/ModalExportDataSelect.tsx
  react/src/dashboard/components/modals/ModalReservationUpload.tsx
  react/src/dashboard/components/modals/ModalVoucherTransactionsUpload.tsx
  react/src/dashboard/components/pages/financial-dashboard-overview/FinancialDashboardOverview.tsx
  react/src/dashboard/components/pages/financial-dashboard-overview/elements/FinancialOverviewFundsBudgetTable.tsx
  react/src/dashboard/components/pages/financial-dashboard-overview/elements/FinancialOverviewFundsBudgetTableItem.tsx
  react/src/dashboard/components/pages/financial-dashboard-overview/elements/FinancialOverviewFundsTable.tsx
  react/src/dashboard/components/pages/financial-dashboard-overview/hooks/useExportFunds.tsx
  react/src/dashboard/components/pages/financial-dashboard/FinancialDashboard.tsx
  react/src/dashboard/components/pages/financial-dashboard/elements/FinancialChart.tsx
  react/src/dashboard/components/pages/financial-dashboard/elements/FinancialFilter.tsx
  react/src/dashboard/components/pages/financial-dashboard/elements/FinancialFilters.tsx
  react/src/dashboard/components/pages/financial-dashboard/elements/FinancialStatistics.tsx
  react/src/dashboard/components/pages/financial-dashboard/elements/ProviderFinancialTable.tsx
  react/src/dashboard/components/pages/financial-dashboard/elements/ProviderFinancialTablesTransactions.tsx
  react/src/dashboard/components/pages/financial-dashboard/types/FinancialStatisticTypes.ts
  react/src/dashboard/components/pages/transaction-bulks-view/TransactionBulksView.tsx
  react/src/dashboard/components/pages/transaction-bulks-view/elements/TransactionBulkTransactionsTable.tsx
  react/src/dashboard/components/pages/transactions-view/elements/TransactionDetails.tsx
  react/src/dashboard/components/pages/transactions/Transactions.tsx
  react/src/dashboard/i18n/i18n-nl.js
  react/src/dashboard/i18n/nl/pages/transaction.pug.i18n.js
  react/src/dashboard/i18n/nl/pages/transactions.pug.i18n.js
  react/src/dashboard/modules/paginator/components/Paginator.tsx
  react/src/dashboard/props/models/Bank.tsx
  react/src/dashboard/props/models/Fund.tsx
  react/src/dashboard/props/models/Transaction.tsx
  react/src/dashboard/props/models/TransactionBulk.tsx
  react/src/dashboard/router/routes.tsx
  react/src/dashboard/services/FundService.ts
  react/src/dashboard/services/OrganizationService.ts
  react/src/dashboard/services/TransactionBulkService.ts
  react/src/dashboard/services/TransactionService.ts
  react/src/dashboard/services/exports/useMakeExporterService.tsx
  react/src/props/EnvData.ts
  react/src/webshop/props/models/Fund.ts
Labels: Urgency: High

#129 Add marketplace pages for funds and voucher topup
  react/assets/forus-platform/resources/_platform-common/assets/img/features/icons/budget-funds/icon-1.svg
  react/assets/forus-platform/resources/_platform-common/assets/img/features/icons/budget-funds/icon-2.svg
  react/assets/forus-platform/resources/_platform-common/assets/img/features/icons/budget-funds/icon-3.svg
  react/assets/forus-platform/resources/_platform-common/assets/img/features/icons/budget-funds/icon-4.svg
  react/assets/forus-platform/resources/_platform-common/assets/img/features/icons/budget_funds.svg
  react/assets/forus-platform/resources/_platform-common/assets/img/features/icons/external-funds/icon-1.svg
  react/assets/forus-platform/resources/_platform-common/assets/img/features/icons/external-funds/icon-2.svg
  react/assets/forus-platform/resources/_platform-common/assets/img/features/icons/external-funds/icon-3.svg
  react/assets/forus-platform/resources/_platform-common/assets/img/features/icons/external-funds/icon-4.svg
  react/assets/forus-platform/resources/_platform-common/assets/img/features/icons/external_funds.svg
  react/assets/forus-platform/resources/_platform-common/assets/img/features/icons/subsidy-funds/icon-1.svg
  react/assets/forus-platform/resources/_platform-common/assets/img/features/icons/subsidy-funds/icon-2.svg
  react/assets/forus-platform/resources/_platform-common/assets/img/features/icons/subsidy-funds/icon-3.svg
  react/assets/forus-platform/resources/_platform-common/assets/img/features/icons/subsidy-funds/icon-4.svg
  react/assets/forus-platform/resources/_platform-common/assets/img/features/icons/subsidy_funds.svg
  react/assets/forus-platform/resources/_platform-common/assets/img/features/icons/voucher-top-up/icon-1.svg
  react/assets/forus-platform/resources/_platform-common/assets/img/features/icons/voucher-top-up/icon-2.svg
  react/assets/forus-platform/resources/_platform-common/assets/img/features/icons/voucher-top-up/icon-3.svg
  react/assets/forus-platform/resources/_platform-common/assets/img/features/icons/voucher-top-up/icon-4.svg
  react/assets/forus-platform/resources/_platform-common/assets/img/features/icons/voucher_top_up.svg
  react/assets/forus-platform/resources/_platform-common/assets/img/features/img/budget-funds/banner-action-bg.jpg
  react/assets/forus-platform/resources/_platform-common/assets/img/features/img/budget-funds/banner.jpg
  react/assets/forus-platform/resources/_platform-common/assets/img/features/img/external-funds/banner-action-bg.jpg
  react/assets/forus-platform/resources/_platform-common/assets/img/features/img/external-funds/banner.jpg
  react/assets/forus-platform/resources/_platform-common/assets/img/features/img/subsidy-funds/banner-action-bg.jpg
  react/assets/forus-platform/resources/_platform-common/assets/img/features/img/subsidy-funds/banner.jpg
  react/assets/forus-platform/resources/_platform-common/assets/img/features/img/voucher-top-up/banner-action-bg.jpg
  react/assets/forus-platform/resources/_platform-common/assets/img/features/img/voucher-top-up/banner.jpg
  react/assets/forus-platform/scss/_common/blocks/marketplace-features/block-feature-list.scss
  react/src/dashboard/components/pages/feature/Feature.tsx
  react/src/dashboard/components/pages/feature/items/BudgetFunds.tsx
  react/src/dashboard/components/pages/feature/items/ExternalFunds.tsx
  react/src/dashboard/components/pages/feature/items/SubsidyFunds.tsx
  react/src/dashboard/components/pages/feature/items/VoucherTopUp.tsx
  react/src/dashboard/services/FeaturesService.ts
Labels: Urgency: Medium

#132 Fix fund request content visible while fetching resources
  react/src/webshop/components/pages/funds-request/FundRequest.tsx
Labels: Urgency: Low

#130 Products add adjustments in the provider dashboard
  react/src/dashboard/components/pages/products/Products.tsx
  react/src/dashboard/components/pages/provider-overview/ProviderOverview.tsx
  react/src/dashboard/services/ProductService.ts
Labels: Urgency: Low

#106 Migrate pre-check page
  react/assets/forus-platform/scss/_common/blocks/block-pre-checks-blocks-editor.scss
  react/assets/forus-platform/scss/_common/includes/helpers.scss
  react/src/dashboard/components/elements/empty-card/EmptyCard.tsx
  react/src/dashboard/components/pages/pre-check/PreCheck.tsx
  react/src/dashboard/components/pages/pre-check/elements/PreCheckStepEditor.tsx
  react/src/dashboard/components/pages/pre-check/elements/PreCheckStepEditorItem.tsx
  react/src/dashboard/components/pages/pre-check/elements/PreCheckStepEditorItemRecord.tsx
  react/src/dashboard/components/pages/pre-check/elements/PreCheckStepEditorItemRecordSettings.tsx
  react/src/dashboard/hooks/useFormBuilder.tsx
  react/src/dashboard/props/models/Implementation.tsx
  react/src/dashboard/props/models/PreCheck.tsx
  react/src/dashboard/props/models/PreCheckRecord.tsx
  react/src/dashboard/props/models/PreCheckRecordSetting.tsx
  react/src/dashboard/router/routes.tsx
  react/src/dashboard/services/ImplementationService.ts
  react/src/dashboard/services/PreCheckService.ts
Labels: Urgency: High

#100 Migrate CSV upload page
  react/assets/forus-platform/scss/_common/blocks/block-bi-info.scss
  react/assets/forus-platform/scss/_common/blocks/block-info-box.scss
  react/assets/forus-platform/scss/_common/components/forms.scss
  react/assets/forus-platform/scss/_common/landing.scss
  react/src/dashboard/components/elements/auth2fa-restriction/Auth2FARestriction.tsx
  react/src/dashboard/components/elements/fund-selector/FundSelector.tsx
  react/src/dashboard/components/modals/ModalCreatePrevalidation.tsx
  react/src/dashboard/components/pages/bi-connection/BiConnection.tsx
  react/src/dashboard/components/pages/csv_validations/CsvValidations.tsx
  react/src/dashboard/components/pages/csv_validations/elements/CSVUpload.tsx
  react/src/dashboard/components/pages/csv_validations/elements/PrevalidatedTable.tsx
  react/src/dashboard/components/pages/csv_validations/elements/ProgressBar.tsx
  react/src/dashboard/hooks/useCopyToClipboard.tsx
  react/src/dashboard/i18n/nl/pages/bi-connection.pug.i18n.js
  react/src/dashboard/props/models/BiConnection.tsx
  react/src/dashboard/props/models/BiConnectionDataType.tsx
  react/src/dashboard/props/models/Fund.tsx
  react/src/dashboard/props/models/FundCriterion.tsx
  react/src/dashboard/props/models/FundRequest.tsx
  react/src/dashboard/props/models/Identity2FAState.tsx
  react/src/dashboard/props/models/Prevalidation.tsx
  react/src/dashboard/props/models/PrevalidationRecord.tsx
  react/src/dashboard/props/models/RecordType.tsx
  react/src/dashboard/router/routes.tsx
  react/src/dashboard/services/BiConnectionService.ts
  react/src/dashboard/services/ClipboardService.ts
  react/src/dashboard/services/FundService.ts
  react/src/dashboard/services/PrevalidationService.ts
  react/src/dashboard/services/RecordTypeService.ts
  react/src/webshop/components/pages/funds-activate/FundActivate.tsx
  react/src/webshop/components/pages/funds-request/FundRequest.tsx
  react/src/webshop/props/models/Fund.ts
  react/src/webshop/props/models/FundCriterion.ts
Labels: Urgency: High

#142 Set permissions for fund actions on implementation page
  react/src/dashboard/components/pages/implementations-view/ImplementationsView.tsx
Labels: Urgency: Medium

#140 Show fund relation information depending on employee permissions
  react/src/dashboard/components/pages/organizations-funds-show/OrganizationsFundsShow.tsx
  react/src/dashboard/components/pages/organizations-funds/OrganizationFunds.tsx
Labels: Urgency: High

#154 ci updates
  .github/dependabot.yml
  .github/workflows/auto_pr_on_master_push.yml
  .github/workflows/compile_and_build.yml
Labels: Scope: Tiny, Urgency: Low
