Repository teamforus/forus-frontend-react, pull requests merged in 2024-07, with the labels that each got.

#137 Wcag alternative texts
  react/src/dashboard/layout/elements/blocks/HeaderNotifications.tsx
  react/src/webshop/components/elements/empty-block/EmptyBlock.tsx
  react/src/webshop/components/elements/lists/funds-list/templates/FundsListItemPreCheck.tsx
  react/src/webshop/components/elements/lists/providers-list/templates/ProvidersListItemList.tsx
  react/src/webshop/components/elements/tooltip/Tooltip.tsx
  react/src/webshop/components/elements/top-navbar/TopNavbar.tsx
  react/src/webshop/components/elements/top-navbar/TopNavbarSearch.tsx
  react/src/webshop/components/pages/auth/Start.tsx
  react/src/webshop/components/pages/funds-activate/FundActivate.tsx
  react/src/webshop/components/pages/funds-request/FundRequest.tsx
  react/src/webshop/components/pages/reimbursements/elements/ReimbursementCard.tsx
  react/src/webshop/components/pages/vouchers-show/VouchersShow.tsx
  react/src/webshop/components/pages/vouchers/elements/VoucherCard.tsx
  react/src/webshop/i18n/i18n-nl.js
  react/src/webshop/layout/elements/LayoutMobileMenu.tsx
  react/src/webshop/services/ProductService.ts
Labels: Urgency: High

#139 WCAG adjust the headers on several pages
  react/assets/forus-webshop/scss/_common/sections/blocks/block-cms-funds.scss
  react/src/webshop/components/elements/cms-blocks/CmsBlocks.tsx
  react/src/webshop/components/elements/lists/products-list/templates/ProductsListItemGrid.tsx
  react/src/webshop/components/elements/lists/products-list/templates/ProductsListItemList.tsx
  react/src/webshop/components/pages/auth/Start.tsx
  react/src/webshop/components/pages/funds-activate/FundActivate.tsx
  react/src/webshop/components/pages/products-show/ProductsShow.tsx
Labels: Urgency: High

#149 Wcag fixes
  react/assets/forus-webshop/scss/_common/sections/blocks/block-funds-list.scss
  react/src/dashboard/components/elements/forms/controls/PincodeControl.tsx
  react/src/dashboard/components/modals/Modal2FADeactivate.tsx
  react/src/dashboard/components/modals/Modal2FASetup.tsx
  react/src/dashboard/components/modals/ModalAuthPincode.tsx
  react/src/webshop/components/modals/Modal2FADeactivate.tsx
  react/src/webshop/components/modals/Modal2FASetup.tsx
  react/src/webshop/components/modals/ModalAuthPincode.tsx
  react/src/webshop/components/modals/ModalPhysicalCardType.tsx
  react/src/webshop/components/pages/funds-activate/FundActivate.tsx
  react/src/webshop/components/pages/funds-show/FundsShow.tsx
  react/src/webshop/components/pages/funds-show/elements/FundFaq.tsx
  react/src/webshop/components/pages/funds-show/elements/FundProductsBlock.tsx
Labels: Urgency: High

#162 Change browser validation message for email input webshop login
  react/src/dashboard/components/elements/forms/ui-controls/UIControlNumber.tsx
  react/src/dashboard/components/elements/forms/ui-controls/UIControlSearch.tsx
  react/src/dashboard/components/elements/forms/ui-controls/UIControlText.tsx
  react/src/dashboard/hooks/useCustomInputValidationMessage.tsx
  react/src/webshop/components/pages/auth/Start.tsx
  react/src/webshop/i18n/nl/pages/signup.js
Labels: Urgency: Medium

#187 Change the fund item block to become clickable
  react/src/webshop/components/elements/lists/funds-list/FundsListItem.tsx
  react/src/webshop/components/elements/lists/funds-list/templates/FundsListItemList.tsx
Labels: Urgency: High

#191 Fix summernote tables format for markdown conversion
  custom.d.ts
  package-lock.json
  package.json
  react/src/dashboard/services/MarkdownService.ts
Labels: Urgency: High

#176 Wcag enhancements for tooltip and expand items
  react/assets/forus-webshop/scss/_common/components/_tooltip.scss
  react/assets/forus-webshop/scss/_common/includes/common.scss
  react/src/dashboard/modules/paginator/components/Paginator.tsx
  react/src/webshop/components/elements/block-showcase/BlockShowcasePage.tsx
  react/src/webshop/components/elements/lists/funds-list/templates/FundsListItemList.tsx
  react/src/webshop/components/elements/lists/providers-list/templates/ProvidersListItemList.tsx
  react/src/webshop/components/elements/tooltip/Tooltip.tsx
  react/src/webshop/components/elements/top-navbar/TopNavbar.tsx
  react/src/webshop/components/elements/top-navbar/TopNavbarSearch.tsx
  react/src/webshop/components/pages/funds-show/elements/FundFaq.tsx
  react/src/webshop/components/pages/products-show/elements/ProductFundsCard.tsx
  react/src/webshop/components/pages/reimbursements-edit/ReimbursementsEdit.tsx
  react/src/webshop/i18n/nl/directives/paginator.js
  react/src/webshop/i18n/nl/layout/navbar.js
  react/src/webshop/i18n/nl/pages/product.js
Labels: Urgency: High

#136 Wcag fix overlap issues
  react/assets/forus-webshop/scss/_common/components/_breadcrumbs.scss
  react/assets/forus-webshop/scss/_common/sections/blocks/block-office.scss
  react/assets/forus-webshop/scss/_common/sections/blocks/block-provider.scss
  react/assets/forus-webshop/scss/_common/sections/blocks/block-showcase.scss
  react/assets/forus-webshop/scss/_common/sections/blocks/profile.scss
  react/assets/forus-webshop/scss/_common/sections/blocks/vouchers.scss
  react/assets/forus-webshop/scss/goereeoverflakkee/sections/faq.scss
  react/assets/forus-webshop/scss/vergoedingen/includes/shame.scss
  react/src/webshop/components/pages/search/Search.tsx
Labels: Urgency: High

#188 Fix the redirect to the csv validations from validator dashboard
  react/src/dashboard/components/pages/csv_validations/CsvValidationsRedirect.tsx
  react/src/dashboard/layout/elements/aside/LayoutAsideValidator.tsx
  react/src/dashboard/router/routes.tsx
Labels: Urgency: Medium

#197 set react version to detect in .eslintrc.js and fix translation setup…
  .eslintrc.js
  react/src/webshop/Webshop.tsx
Labels: Urgency: High

#145 Wcag some enhancements and fixes
  react/assets/forus-webshop/scss/_common/includes/common.scss
  react/assets/forus-webshop/scss/_common/sections/blocks/block-file-uploader.scss
  react/src/webshop/components/elements/file-uploader/FileUploader.tsx
  react/src/webshop/components/elements/lists/products-list/templates/ProductsListItemGrid.tsx
  react/src/webshop/components/elements/lists/products-list/templates/ProductsListItemList.tsx
  react/src/webshop/components/pages/products/Products.tsx
  react/src/webshop/components/pages/reimbursements-edit/ReimbursementsEdit.tsx
Labels: Urgency: High

#202 Replace Zoho Desk chat with Zendesk
  react/public/index.ejs
Labels: Urgency: High

#203 markdown block - convert h4 before table to caption and fix first row…
  react/assets/forus-platform/scss/_common/blocks/block-markdown.scss
  react/assets/forus-webshop/scss/_common/sections/blocks/block-markdown.scss
  react/src/webshop/components/elements/markdown/Markdown.tsx
Labels: Urgency: High

#163 Add wcag suffix for page title
  react/src/dashboard/components/pages/implementations-cms/ImplementationsCms.tsx
  react/src/dashboard/hooks/useTranslate.tsx
  react/src/dashboard/i18n/i18n-nl.js
  react/src/dashboard/props/models/Implementation.tsx
  react/src/dashboard/services/ConfigService.ts
  react/src/webshop/Webshop.tsx
  react/src/webshop/components/pages/auth/Start.tsx
  react/src/webshop/components/pages/fund-requests-show/FundRequestsShow.tsx
  react/src/webshop/components/pages/funds-activate/FundActivate.tsx
  react/src/webshop/components/pages/funds-show/FundsShow.tsx
  react/src/webshop/components/pages/funds/Funds.tsx
  react/src/webshop/components/pages/home/Home.tsx
  react/src/webshop/components/pages/products/Products.tsx
  react/src/webshop/components/pages/vouchers-show/VouchersShow.tsx
  react/src/webshop/contexts/MainContext.tsx
  react/src/webshop/contexts/TitleContext.tsx
  react/src/webshop/hooks/useSetTitle.tsx
  react/src/webshop/i18n/i18n-nl.js
  react/src/webshop/i18n/nl/pages/signup.js
Labels: Urgency: High

#133 fund criteria steps and rules feature
  react/assets/forus-webshop/scss/_common/components/_ui-controls.scss
  react/assets/forus-webshop/scss/_common/sections/blocks/block-file-uploader.scss
  react/assets/forus-webshop/scss/_common/sections/blocks/block-sign_up.scss
  react/src/dashboard/components/elements/forms/ui-controls/UIControlCheckbox.tsx
  react/src/dashboard/props/models/Fund.tsx
  react/src/dashboard/props/models/FundCriteriaStep.ts
  react/src/dashboard/props/models/FundCriterion.tsx
  react/src/dashboard/props/models/FundCriterionRule.ts
  react/src/dashboard/props/models/RecordType.tsx
  react/src/webshop/components/elements/file-uploader/FileUploader.tsx
  react/src/webshop/components/elements/file-uploader/FileUploaderItemView.tsx
  react/src/webshop/components/elements/markdown/Markdown.tsx
  react/src/webshop/components/pages/fund-requests-show/elements/FundRequestRecordClarificationCard.tsx
  react/src/webshop/components/pages/funds-request/FundRequest.tsx
  react/src/webshop/components/pages/funds-request/elements/FundRequestProgress.tsx
  react/src/webshop/components/pages/funds-request/elements/steps/FundRequestStepCriteria.tsx
  react/src/webshop/components/pages/funds-request/elements/steps/FundRequestStepCriteriaOverview.tsx
  react/src/webshop/components/pages/funds-request/elements/steps/FundRequestStepOverview.tsx
  react/src/webshop/components/pages/funds-request/hooks/useShouldRequestRecord.ts
  react/src/webshop/components/pages/reimbursements-edit/ReimbursementsEdit.tsx
  react/src/webshop/props/models/Fund.ts
Labels: Urgency: Medium

#201 extra payment feature for empty vouchers
  react/assets/forus-webshop/scss/_common/components/_modals.scss
  react/assets/forus-webshop/scss/style-webshop-general-vars.scss
  react/src/dashboard/components/elements/forms/controls/ToggleControl.tsx
  react/src/dashboard/components/pages/fund-provider/FundProvider.tsx
  react/src/dashboard/components/pages/sponsor-provider-organization/elements/ProviderOrganizationOverview.tsx
  react/src/dashboard/props/models/FundProvider.tsx
  react/src/webshop/components/modals/modal-product-reserve/ModalProductReserve.tsx
  react/src/webshop/components/pages/reservations-show/ReservationsShow.tsx
  react/src/webshop/components/pages/reservations/elements/ReservationCard.tsx
Labels: Urgency: High

#207 WCAG fixes
  react/assets/forus-platform/scss/_common/blocks/block-email-log-preview.scss
  react/assets/forus-platform/scss/_common/dashboard.scss
  react/assets/forus-webshop/scss/_common/components/_ui-controls.scss
  react/assets/forus-webshop/scss/_common/sections/blocks/block-file-uploader.scss
  react/assets/forus-webshop/scss/_common/sections/blocks/block-sign_up.scss
  react/src/dashboard/components/elements/block-card-emails/BlockCardEmails.tsx
  react/src/dashboard/components/elements/block-card-notes/BlockCardNotes.tsx
  react/src/dashboard/components/elements/forms/ui-controls/UIControlCheckbox.tsx
  react/src/dashboard/components/modals/ModalLogEmailShow.tsx
  react/src/dashboard/components/pages/fund-requests-view/FundRequestsView.tsx
  react/src/dashboard/components/pages/fund-requests-view/elements/FundRequestPerson.tsx
  react/src/dashboard/components/pages/fund-requests-view/elements/FundRequestRecordTabs.tsx
  react/src/dashboard/components/pages/fund-requests-view/elements/record-tabs/FundRequestRecordAttachmentsTab.tsx
  react/src/dashboard/components/pages/fund-requests-view/elements/record-tabs/FundRequestRecordClarificationsTab.tsx
  react/src/dashboard/components/pages/fund-requests-view/elements/record-tabs/FundRequestRecordHistoryTab.tsx
  react/src/dashboard/components/pages/fund-requests/FundRequests.tsx
  react/src/dashboard/components/pages/implementations-notifications-edit/ImplementationsNotificationsEdit.tsx
  react/src/dashboard/components/pages/implementations-notifications-edit/elements/SystemNotificationEditor.tsx
  react/src/dashboard/components/pages/reimbursements-view/ReimbursementsView.tsx
  react/src/dashboard/components/pages/vouchers-view/VouchersViewComponent.tsx
  react/src/dashboard/helpers/utils.ts
  react/src/dashboard/props/ApiResponses.ts
  react/src/dashboard/props/models/EmailLog.tsx
  react/src/dashboard/props/models/Fund.tsx
  react/src/dashboard/props/models/FundCriteriaStep.ts
  react/src/dashboard/props/models/FundCriterion.tsx
  react/src/dashboard/props/models/FundCriterionRule.ts
  react/src/dashboard/props/models/RecordType.tsx
  react/src/dashboard/props/models/SystemNotification.tsx
  react/src/dashboard/router/routes.tsx
  react/src/dashboard/services/FundRequestValidatorService.ts
  react/src/dashboard/services/ImplementationNotificationService.tsx
  react/src/webshop/components/elements/cms-blocks/CmsBlocks.tsx
  react/src/webshop/components/elements/file-uploader/FileUploader.tsx
  react/src/webshop/components/elements/file-uploader/FileUploaderItemView.tsx
  react/src/webshop/components/elements/markdown/Markdown.tsx
  react/src/webshop/components/pages/fund-requests-show/elements/FundRequestRecordClarificationCard.tsx
  react/src/webshop/components/pages/funds-request/FundRequest.tsx
  react/src/webshop/components/pages/funds-request/elements/FundRequestProgress.tsx
  react/src/webshop/components/pages/funds-request/elements/steps/FundRequestStepCriteria.tsx
  react/src/webshop/components/pages/funds-request/elements/steps/FundRequestStepCriteriaOverview.tsx
  react/src/webshop/components/pages/funds-request/elements/steps/FundRequestStepOverview.tsx
  react/src/webshop/components/pages/funds-request/hooks/useShouldRequestRecord.ts
  react/src/webshop/components/pages/funds-show/elements/FundFaq.tsx
  react/src/webshop/components/pages/reimbursements-edit/ReimbursementsEdit.tsx
  react/src/webshop/i18n/i18n-nl.js
  react/src/webshop/props/models/Fund.ts
Labels: Urgency: High

#210 fix the hover effect of Vergoedingen navbar search button
  react/assets/forus-webshop/scss/vergoedingen/includes/shame.scss
  react/src/webshop/components/elements/top-navbar/TopNavbar.tsx
  react/src/webshop/components/elements/top-navbar/TopNavbarSearch.tsx
Labels: Scope: Tiny, Urgency: High

#213 add Google Tag Manager to the website
  env.example.js
  package-lock.json
  package.json
  react/public/index.ejs
  react/src/props/EnvDataWebshopProp.ts
  react/src/website/Website.tsx
  react/src/website/modules/google_tag_manager/GoogleTagManager.tsx
Labels: Urgency: High

#212 Rename vouchers to tegoeden
  react/src/dashboard/components/modals/ModalReservationCreate.tsx
  react/src/dashboard/components/pages/identitities-show/elements/IdentityVouchersCard.tsx
  react/src/dashboard/components/pages/identity-security/Security2FA.tsx
  react/src/dashboard/components/pages/implementations-notifications-send/ImplementationsNotificationsSend.tsx
  react/src/dashboard/components/pages/organizations-funds-show/elements/OrganizationsFundsShowIdentitiesCard.tsx
  react/src/dashboard/components/pages/transactions-view/elements/TransactionDetails.tsx
  react/src/dashboard/components/pages/vouchers-view/VouchersViewComponent.tsx
  react/src/dashboard/i18n/en/modals/modal-voucher-create.js
  react/src/dashboard/i18n/en/modals/modal-voucher-qr_code.js
  react/src/dashboard/i18n/en/pages/vouchers.js
  react/src/dashboard/i18n/i18n-nl.js
  react/src/dashboard/i18n/nl/pages/reimbursements.js
  react/src/dashboard/i18n/nl/pages/vouchers.js
Labels: Scope: Tiny, Urgency: High

#211 Add label for search input on webshop
  react/assets/forus-webshop/scss/_common/sections/blocks/block-navbar-search.scss
  react/assets/forus-webshop/scss/doetegoed/sections/blocks/block-navbar-search.scss
  react/assets/forus-webshop/scss/doetegoed/sections/blocks/block-navbar.scss
  react/assets/forus-webshop/scss/eemsdelta/sections/blocks/block-navbar-search.scss
  react/assets/forus-webshop/scss/eemsdelta/sections/blocks/block-navbar.scss
  react/assets/forus-webshop/scss/groningen/sections/blocks/block-navbar-search.scss
  react/assets/forus-webshop/scss/groningen/sections/blocks/block-navbar.scss
  react/assets/forus-webshop/scss/style-webshop-doetegoed.scss
  react/assets/forus-webshop/scss/style-webshop-eemsdelta.scss
  react/assets/forus-webshop/scss/style-webshop-groningen.scss
  react/assets/forus-webshop/scss/vergoedingen/includes/shame.scss
  react/src/webshop/components/elements/top-navbar/TopNavbarSearch.tsx
  react/src/webshop/components/pages/funds-pre-check/FundsPreCheck.tsx
  react/src/webshop/components/pages/funds/Funds.tsx
  react/src/webshop/components/pages/providers/Providers.tsx
  react/src/webshop/components/pages/reservations/Reservations.tsx
  react/src/webshop/i18n/i18n-nl.js
  react/src/webshop/i18n/nl/pages/funds.js
  react/src/webshop/i18n/nl/pages/providers.js
  react/src/webshop/i18n/nl/pages/reservations.js
Labels: Urgency: High

#173 add exception boundaries
  package-lock.json
  package.json
  react/assets/forus-platform/scss/_common/dashboard.scss
  react/assets/forus-webshop/scss/_common/sections/blocks/block-exception.scss
  react/assets/forus-webshop/scss/webshop.scss
  react/src/dashboard/components/elements/error-boundary-handler/ErrorBoundaryHandler.tsx
  react/src/dashboard/layout/Layout.tsx
  react/src/webshop/components/elements/block-showcase/BlockShowcasePage.tsx
  react/src/webshop/components/elements/block-showcase/BlockShowcaseProfile.tsx
  react/src/webshop/components/pages/block-exception/BlockException.tsx
  react/src/webshop/layout/Layout.tsx
Labels: Urgency: Medium

#228 wcag: fix contrast on ui-controls clear button and tab focus issue an…
  react/assets/forus-webshop/scss/_common/components/_form.scss
  react/assets/forus-webshop/scss/_common/components/_ui-controls.scss
  react/assets/forus-website/scss/components/form.scss
  react/src/dashboard/components/elements/forms/ui-controls/UIControlNumber.tsx
  react/src/dashboard/components/elements/forms/ui-controls/UIControlSearch.tsx
  react/src/dashboard/components/elements/forms/ui-controls/UIControlText.tsx
  react/src/webshop/components/pages/funds-pre-check/FundsPreCheck.tsx
  react/src/webshop/components/pages/funds/Funds.tsx
  react/src/webshop/components/pages/products/Products.tsx
  react/src/webshop/components/pages/providers/Providers.tsx
  react/src/webshop/components/pages/reservations/Reservations.tsx
Labels: Urgency: High

#234 Make logo not clickable for home page on webshop
  react/src/webshop/components/elements/top-navbar/TopNavbar.tsx
Labels: Urgency: High

#233 WCAG minor fixes
  react/src/webshop/components/elements/lists/funds-list/templates/FundsListItemList.tsx
  react/src/webshop/components/elements/top-navbar/TopNavbarSearch.tsx
  react/src/webshop/i18n/i18n-nl.js
  react/src/webshop/i18n/nl/pages/funds.js
Labels: Urgency: High

#237 aria labels translations
  react/src/dashboard/components/elements/forms/ui-controls/UIControlDate.tsx
  react/src/dashboard/components/elements/forms/ui-controls/UIControlNumber.tsx
  react/src/dashboard/components/elements/forms/ui-controls/UIControlStep.tsx
  react/src/dashboard/components/elements/forms/ui-controls/UIControlText.tsx
  react/src/dashboard/components/elements/select-control/templates/SelectControlOptions.tsx
  react/src/dashboard/components/elements/select-control/templates/SelectControlOptionsCountryCodes.tsx
  react/src/dashboard/components/elements/select-control/templates/SelectControlOptionsFund.tsx
  react/src/webshop/components/elements/lists/products-list/templates/ProductsListItemGrid.tsx
  react/src/webshop/components/elements/lists/products-list/templates/ProductsListItemList.tsx
  react/src/webshop/components/elements/select-control/templates/SelectControlOptionsVouchers.tsx
  react/src/webshop/components/elements/top-navbar/TopNavbar.tsx
  react/src/webshop/components/pages/identity-emails/PreferencesEmails.tsx
  react/src/webshop/components/pages/products-show/ProductsShow.tsx
  react/src/webshop/components/pages/products/Products.tsx
  react/src/webshop/components/pages/providers/Providers.tsx
  react/src/webshop/layout/elements/LayoutMobileMenu.tsx
Labels: Scope: Tiny, Urgency: Medium

#236 WCAG filter enhancement on mobile, add table scrollable
  react/assets/forus-platform/scss/_common/blocks/block-markdown.scss
  react/assets/forus-webshop/scss/_common/sections/blocks/block-cms.scss
  react/assets/forus-webshop/scss/_common/sections/blocks/block-markdown.scss
  react/assets/forus-webshop/scss/_common/sections/blocks/block-showcase.scss
  react/src/webshop/components/elements/block-showcase/BlockShowcasePage.tsx
  react/src/webshop/components/elements/markdown/Markdown.tsx
  react/src/webshop/components/elements/top-navbar/TopNavbar.tsx
  react/src/webshop/components/pages/products/Products.tsx
  react/src/webshop/i18n/nl/layout/navbar.js
Labels: Urgency: High

#238 remove uppercase for nijmegen
  react/assets/forus-webshop/scss/_common/components/_buttons.scss
  react/assets/forus-webshop/scss/_common/sections/blocks/voucher.scss
  react/assets/forus-webshop/scss/style-webshop-berkelland-vars.scss
  react/assets/forus-webshop/scss/style-webshop-doetegoed-vars.scss
  react/assets/forus-webshop/scss/style-webshop-ede-vars.scss
  react/assets/forus-webshop/scss/style-webshop-eemsdelta-vars.scss
  react/assets/forus-webshop/scss/style-webshop-geertruidenberg-vars.scss
  react/assets/forus-webshop/scss/style-webshop-general-vars.scss
  react/assets/forus-webshop/scss/style-webshop-goereeoverflakkee-vars.scss
  react/assets/forus-webshop/scss/style-webshop-groningen-vars.scss
  react/assets/forus-webshop/scss/style-webshop-hartvanwestbrabant-vars.scss
  react/assets/forus-webshop/scss/style-webshop-heumen-vars.scss
  react/assets/forus-webshop/scss/style-webshop-kerstpakket-vars.scss
  react/assets/forus-webshop/scss/style-webshop-noordoostpolder-vars.scss
  react/assets/forus-webshop/scss/style-webshop-oostgelre-vars.scss
  react/assets/forus-webshop/scss/style-webshop-potjeswijzer-vars.scss
  react/assets/forus-webshop/scss/style-webshop-schagen-vars.scss
  react/assets/forus-webshop/scss/style-webshop-vergoedingen-vars.scss
  react/assets/forus-webshop/scss/style-webshop-waalwijk-vars.scss
  react/assets/forus-webshop/scss/style-webshop-winterswijk-vars.scss
  react/assets/forus-webshop/scss/vergoedingen/includes/shame.scss
Labels: Scope: Tiny, Urgency: Low

#235 Hide voucher amount in table if no budget funds
  react/src/dashboard/components/pages/vouchers/Vouchers.tsx
Labels: Scope: Tiny, Urgency: Medium

#185 Add backend layout
  env.example.js
  react/assets/forus-backend/resources/_backend-common/assets/css/notification-styles.css
  react/assets/forus-backend/resources/_backend-common/assets/img/icon-2fa-authenticator.svg
  react/assets/forus-backend/resources/_backend-common/assets/img/icon-2fa-phone.svg
  react/assets/forus-backend/resources/_backend-common/assets/img/icon-app/app-store-android.svg
  react/assets/forus-backend/resources/_backend-common/assets/img/icon-app/app-store-ios.svg
  react/assets/forus-backend/resources/_backend-common/assets/img/me-logo-react.png
  react/assets/forus-backend/resources/_backend-common/assets/img/sign_in-pin_code-error.svg
  react/assets/forus-backend/resources/_backend-common/assets/img/sign_in-pin_code-instruction.png
  react/assets/forus-backend/resources/_backend-common/assets/img/sign_in-pin_code-success.svg
  react/assets/forus-backend/scss/blocks/block-auth-pin_code.scss
  react/assets/forus-backend/scss/blocks/block-missing-app.scss
  react/assets/forus-backend/scss/blocks/block-pincode.scss
  react/assets/forus-backend/scss/blocks/block-sign_up.scss
  react/assets/forus-backend/scss/style.scss
  react/assets/forus-backend/scss/vars.scss
  react/public/index.ejs
  react/src/backend/Backend.tsx
  react/src/backend/components/pages/Auth2FA.tsx
  react/src/backend/contexts/AuthContext.tsx
  react/src/backend/contexts/MainContext.tsx
  react/src/backend/hooks/useAssetUrl.tsx
  react/src/backend/hooks/useEnvData.tsx
  react/src/dashboard/components/modals/Modal2FASetup.tsx
  react/src/dashboard/components/pages/auth/Auth2FA.tsx
  react/src/dashboard/components/pages/identity-security/Security2FA.tsx
  react/src/dashboard/services/IdentityService.ts
  react/src/index-backend.js
  react/src/props/EnvDataBackend.ts
  webpack.config.js
Labels: Urgency: Medium
